version: "3.8"

services: 
  app: 
    image: node:12-alpine
    command: sh -c "npm install && npm run dev"
    ports: 
      - 5000:5000
    working_dir: /app
    volumes: 
      - ./:/app
    environment: 
      PORT: 5000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    volumes: 
      - /pgdata:/var/lib/postgresql/pgdata