version: "3.8"

services: 
  app: 
    image: docker-learn
    ports: 
      - 4000:4000
    depends_on: 
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13092005
      POSTGRES_DB: learn-docker-db
    ports:
    - 5432:5432
    volumes: 
      - ./pgdata:/var/lib/postgresql/pgdata