version: "3.8"

services: 
  app: 
    image: node:12-alpine
    command: sh -c "npm install && npm start"
    ports: 
      - 5000:5000
    working_dir: /src
    volumes: 
      - ./:/src
    environment: 
      PORT: 5000